QuorumServer {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    user_${ZK_SASL_USER}="${ZK_SASL_PASS}";
};
QuorumLearner {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="${ZK_SASL_USER}"
    password="${ZK_SASL_PASS}";
};
Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    user_${ZK_SASL_USER}="${ZK_SASL_PASS}";
};
