# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "aithena-common",
# ]
#
# [tool.uv.sources]
# aithena-common = { path = "../src/aithena-common" }
# ///

from __future__ import annotations

import argparse
import contextlib
import getpass
import os
import secrets
import shutil
import sqlite3
import stat
import subprocess  # noqa: S404 — used for git operations with list args, never shell=True
import sys
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from urllib.parse import urlparse

from aithena_common.auth_db import find_user as _common_find_user
from aithena_common.auth_db import init_auth_db
from aithena_common.passwords import hash_password

ROOT = Path(__file__).resolve().parents[1]

DEFAULT_AUTH_DB_PATH = Path.home() / ".local" / "share" / "aithena" / "auth" / "users.db"
DEFAULT_CONTAINER_AUTH_DB_PATH = "/data/auth/users.db"
DEFAULT_AUTH_COOKIE_NAME = "aithena_auth"
DEFAULT_AUTH_JWT_TTL = "24h"
DEFAULT_PUBLIC_ORIGIN = "http://localhost"
DEFAULT_ENV_PATH = ROOT / ".env"
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_RABBITMQ_USER = "aithena"
INSECURE_JWT_SECRETS = {"", "change-me", "development-only-change-me", "generate-with-installer"}
INSECURE_RABBITMQ_USERS = {"", "change-me", "guest", "generate-with-installer"}
INSECURE_RABBITMQ_PASSWORDS = {"", "change-me", "guest", "generate-with-installer"}
# Per-service RabbitMQ users (names are fixed; only passwords are generated)
RABBITMQ_SERVICE_USERS = ("lister", "indexer", "search", "admin")
INSECURE_RABBITMQ_SERVICE_PASSWORDS = {
    "",
    "change-me",
    "generate-with-installer",
    "lister_dev_pass",
    "indexer_dev_pass",
    "search_dev_pass",
    "admin_dev_pass",
}
DEFAULT_SOLR_ADMIN_USER = "solr_admin"
DEFAULT_SOLR_READONLY_USER = "solr_read"
INSECURE_SOLR_PASSWORDS = {"", "change-me", "SolrAdmin_dev2024!", "SolrRead_dev2024!", "generate-with-installer"}
ENV_COMMENTS: list[tuple[str, str]] = [
    ("BOOKS_PATH", "Path to your book library on the host"),
    ("BOOK_LIBRARY_PATH", "Compatibility alias for installer consumers"),
    ("PUBLIC_ORIGIN", "Public origin used by browsers (scheme + host)"),
    ("CORS_ORIGINS", "Comma-separated CORS origins consumed by solr-search"),
    ("AUTH_DB_DIR", "Host directory mounted into the container for auth storage"),
    ("AUTH_DB_PATH", "SQLite auth database path inside the container"),
    ("AUTH_JWT_SECRET", "JWT signing secret generated by the installer"),
    ("AUTH_JWT_TTL", "JWT lifetime accepted by src/solr-search/auth.py (e.g. 24h)"),
    ("AUTH_COOKIE_NAME", "HTTP cookie name used for browser auth"),
    ("AUTH_ADMIN_USERNAME", "Installer-managed bootstrap admin username"),
    ("AUTH_ADMIN_PASSWORD", "Bootstrap admin password created by the installer"),
    ("RABBITMQ_USER", "RabbitMQ legacy admin username (kept for backwards compat)"),
    ("RABBITMQ_PASS", "RabbitMQ legacy admin password (kept for backwards compat)"),
    ("RABBITMQ_LISTER_USER", "RabbitMQ user for document-lister (publish to documents exchange)"),
    ("RABBITMQ_LISTER_PASS", "Password for RabbitMQ lister user"),
    ("RABBITMQ_INDEXER_USER", "RabbitMQ user for document-indexer (consume from queues)"),
    ("RABBITMQ_INDEXER_PASS", "Password for RabbitMQ indexer user"),
    ("RABBITMQ_SEARCH_USER", "RabbitMQ user for solr-search (publish + monitoring)"),
    ("RABBITMQ_SEARCH_PASS", "Password for RabbitMQ search user"),
    ("RABBITMQ_ADMIN_USER", "RabbitMQ admin user for management UI"),
    ("RABBITMQ_ADMIN_PASS", "Password for RabbitMQ admin user"),
    ("SOLR_ADMIN_USER", "Solr admin username for collection management and security"),
    ("SOLR_ADMIN_PASS", "Solr admin password (generated by installer)"),
    ("SOLR_READONLY_USER", "Solr readonly username for search queries"),
    ("SOLR_READONLY_PASS", "Solr readonly password (generated by installer)"),
    ("SOLR_TOPOLOGY", "Deployment topology: single-node (1 Solr + 1 ZK) or distributed (3+3)"),
    ("VERSION", "Container build metadata (defaults to VERSION file)"),
    ("GIT_COMMIT", "Container build metadata (defaults to current HEAD)"),
    ("BUILD_DATE", "Container build metadata timestamp"),
]


@dataclass(frozen=True)
class InstallerConfig:
    library_path: str | None = None
    admin_user: str | None = None
    admin_password: str | None = None
    origin: str | None = None
    auth_db_path: Path | None = None
    env_path: Path = DEFAULT_ENV_PATH
    reset: bool = False
    environment: str | None = None  # "dev" or "prod"
    gpu: str | None = None  # "nvidia", "intel", or "none"
    ssl: bool | None = None
    domain: str | None = None
    topology: str | None = None  # "single-node" or "distributed"


@dataclass(frozen=True)
class SetupResult:
    env_path: Path
    auth_db_path: Path
    library_path: Path
    origin: str
    admin_user: str
    admin_action: str
    generated_jwt_secret: bool
    generated_solr_passwords: bool
    environment: str = "prod"
    gpu: str = "none"
    ssl: bool = False
    domain: str | None = None
    topology: str = "distributed"
    start_script: Path | None = None


def load_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    env_values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#") or "=" not in raw_line:
            continue
        key, value = raw_line.split("=", 1)
        env_values[key.strip()] = _unquote_env_value(value.strip())
    return env_values


def write_env_file(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# Generated by installer/setup.py on {utc_now_iso()}", ""]
    for key, comment in ENV_COMMENTS:
        if key not in values:
            continue
        value = values[key]
        lines.append(f"# {comment}")
        lines.append(f"{key}={_quote_env_value(value)}")
        lines.append("")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    with contextlib.suppress(OSError):
        path.chmod(0o600)


def resolve_library_path(raw_value: str) -> Path:
    candidate = Path(raw_value).expanduser()
    if candidate.exists() and not candidate.is_dir():
        raise ValueError("Book library path must point to a directory")
    candidate.mkdir(parents=True, exist_ok=True)
    return candidate.resolve()


def resolve_auth_db_path(raw_value: str) -> Path:
    candidate = Path(raw_value).expanduser()
    if candidate.exists() and candidate.is_dir():
        raise ValueError("Auth DB path must be a file path, not a directory")
    return candidate.resolve()


def normalize_username(raw_value: str) -> str:
    username = raw_value.strip()
    if not username:
        raise ValueError("Admin username is required")
    if any(c in username for c in ("\n", "\r", "\x00", "=")):
        raise ValueError("Username contains invalid characters")
    return username


def normalize_origin(raw_value: str) -> str:
    parsed = urlparse(raw_value.strip())
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError("Origin must be a full http:// or https:// URL")
    if parsed.params or parsed.query or parsed.fragment:
        raise ValueError("Origin must not include params, query strings, or fragments")
    cleaned_path = parsed.path.rstrip("/")
    if cleaned_path:
        raise ValueError("Origin must not include a path")
    return f"{parsed.scheme}://{parsed.netloc}".rstrip("/")


def bootstrap_admin_user(
    db_path: Path,
    username: str,
    password: str | None,
    *,
    reset: bool = False,
) -> str:
    if reset and db_path.exists():
        db_path.unlink()

    init_auth_db(db_path)
    with contextlib.suppress(OSError):
        db_path.chmod(0o600)
    normalized_username = normalize_username(username)

    with sqlite3.connect(db_path) as connection:
        connection.row_factory = sqlite3.Row
        existing_row = connection.execute(
            "SELECT id, role FROM users WHERE username = ?",
            (normalized_username,),
        ).fetchone()

        if existing_row is None and password is None:
            raise ValueError("Admin password is required when creating a new admin user")

        if existing_row is None:
            connection.execute(
                "INSERT INTO users (username, password_hash, role) VALUES (?, ?, ?)",
                (normalized_username, hash_password(password or ""), "admin"),
            )
            connection.commit()
            return "created"

        if password is None and existing_row["role"] == "admin":
            return "kept"

        if password is None:
            connection.execute(
                "UPDATE users SET role = ? WHERE id = ?",
                ("admin", int(existing_row["id"])),
            )
            connection.commit()
            return "updated"

        connection.execute(
            "UPDATE users SET password_hash = ?, role = ? WHERE id = ?",
            (hash_password(password), "admin", int(existing_row["id"])),
        )
        connection.commit()
        return "updated"


def find_user(db_path: Path, username: str) -> dict[str, str | int] | None:
    """Look up a user by username, delegating to the shared library."""
    normalized = normalize_username(username)
    return _common_find_user(db_path, normalized)


def build_env_values(
    *,
    library_path: Path,
    auth_db_path: Path,
    origin: str,
    admin_user: str,
    admin_password: str | None,
    existing_env: dict[str, str],
    secret_factory: Callable[[int], str],
    reset: bool,
) -> tuple[dict[str, str], bool, bool]:
    existing_secret = existing_env.get("AUTH_JWT_SECRET", "")
    generated_jwt_secret = reset or existing_secret in INSECURE_JWT_SECRETS
    auth_jwt_secret = existing_secret or secret_factory(32)
    if generated_jwt_secret:
        auth_jwt_secret = secret_factory(32)

    existing_rabbitmq_user = existing_env.get("RABBITMQ_USER", "").strip()
    rabbitmq_user = existing_rabbitmq_user or DEFAULT_RABBITMQ_USER
    if reset or existing_rabbitmq_user in INSECURE_RABBITMQ_USERS:
        rabbitmq_user = DEFAULT_RABBITMQ_USER

    existing_rabbitmq_pass = existing_env.get("RABBITMQ_PASS", "")
    rabbitmq_pass = existing_rabbitmq_pass
    if reset or existing_rabbitmq_pass in INSECURE_RABBITMQ_PASSWORDS:
        rabbitmq_pass = secret_factory(32)

    # Per-service RabbitMQ passwords -- each service gets a unique credential.
    # Usernames are fixed (lister, indexer, search, admin); only passwords rotate.
    rabbitmq_service_passwords: dict[str, str] = {}
    for svc_name in RABBITMQ_SERVICE_USERS:
        env_key = f"RABBITMQ_{svc_name.upper()}_PASS"
        existing_svc_pass = existing_env.get(env_key, "")
        if reset or existing_svc_pass in INSECURE_RABBITMQ_SERVICE_PASSWORDS:
            rabbitmq_service_passwords[svc_name] = secret_factory(32)
        else:
            rabbitmq_service_passwords[svc_name] = existing_svc_pass

    existing_admin_api_key = existing_env.get("ADMIN_API_KEY", "")
    admin_api_key = existing_admin_api_key
    if reset or not existing_admin_api_key:
        admin_api_key = secret_factory(32)

    # Solr credentials
    existing_solr_admin_pass = existing_env.get("SOLR_ADMIN_PASS", "")
    solr_admin_pass = existing_solr_admin_pass
    if reset or existing_solr_admin_pass in INSECURE_SOLR_PASSWORDS:
        solr_admin_pass = secret_factory(32)

    existing_solr_readonly_pass = existing_env.get("SOLR_READONLY_PASS", "")
    solr_readonly_pass = existing_solr_readonly_pass
    if reset or existing_solr_readonly_pass in INSECURE_SOLR_PASSWORDS:
        solr_readonly_pass = secret_factory(32)

    env_values = {
        "BOOKS_PATH": str(library_path),
        "BOOK_LIBRARY_PATH": str(library_path),
        "PUBLIC_ORIGIN": origin,
        "CORS_ORIGINS": origin,
        "AUTH_DB_DIR": str(auth_db_path.parent),
        "AUTH_DB_PATH": f"/data/auth/{auth_db_path.name}",
        "AUTH_JWT_SECRET": auth_jwt_secret,
        "AUTH_JWT_TTL": existing_env.get("AUTH_JWT_TTL", DEFAULT_AUTH_JWT_TTL),
        "AUTH_COOKIE_NAME": existing_env.get("AUTH_COOKIE_NAME", DEFAULT_AUTH_COOKIE_NAME),
        "AUTH_ADMIN_USERNAME": admin_user,
        "AUTH_ADMIN_PASSWORD": admin_password or existing_env.get("AUTH_ADMIN_PASSWORD", ""),
        "ADMIN_API_KEY": admin_api_key,
        "RABBITMQ_USER": rabbitmq_user,
        "RABBITMQ_PASS": rabbitmq_pass,
        "RABBITMQ_LISTER_USER": "lister",
        "RABBITMQ_LISTER_PASS": rabbitmq_service_passwords["lister"],
        "RABBITMQ_INDEXER_USER": "indexer",
        "RABBITMQ_INDEXER_PASS": rabbitmq_service_passwords["indexer"],
        "RABBITMQ_SEARCH_USER": "search",
        "RABBITMQ_SEARCH_PASS": rabbitmq_service_passwords["search"],
        "RABBITMQ_ADMIN_USER": "admin",
        "RABBITMQ_ADMIN_PASS": rabbitmq_service_passwords["admin"],
        "SOLR_ADMIN_USER": existing_env.get("SOLR_ADMIN_USER", DEFAULT_SOLR_ADMIN_USER),
        "SOLR_ADMIN_PASS": solr_admin_pass,
        "SOLR_READONLY_USER": existing_env.get("SOLR_READONLY_USER", DEFAULT_SOLR_READONLY_USER),
        "SOLR_READONLY_PASS": solr_readonly_pass,
        "VERSION": existing_env.get("VERSION", read_repo_version()),
        "GIT_COMMIT": existing_env.get("GIT_COMMIT", read_git_commit()),
        "BUILD_DATE": existing_env.get("BUILD_DATE", utc_now_iso()),
    }
    generated_solr_passwords = (
        solr_admin_pass != existing_solr_admin_pass or solr_readonly_pass != existing_solr_readonly_pass
    )
    return env_values, generated_jwt_secret, generated_solr_passwords


def detect_gpu() -> str | None:
    """Auto-detect GPU hardware. Returns 'nvidia', 'intel', or None."""
    nvidia_smi = shutil.which("nvidia-smi")
    if nvidia_smi is not None:
        result = subprocess.run(  # noqa: S603
            [nvidia_smi],
            capture_output=True,
            check=False,
        )
        if result.returncode == 0:
            return "nvidia"

    if Path("/dev/dri").is_dir():
        return "intel"

    return None


def resolve_gpu_choice(
    *,
    provided: str | None,
    interactive: bool,
) -> str:
    """Determine GPU choice: 'nvidia', 'intel', or 'none'."""
    if provided is not None:
        if provided not in {"nvidia", "intel", "none"}:
            raise ValueError("--gpu must be 'nvidia', 'intel', or 'none'")
        return provided

    detected = detect_gpu()
    if not interactive:
        return detected or "none"

    if detected == "nvidia":
        answer = prompt_yes_no("Detected NVIDIA GPU. Use GPU acceleration?", default=True)
        return "nvidia" if answer else "none"
    if detected == "intel":
        answer = prompt_yes_no("Detected Intel GPU. Use GPU acceleration?", default=True)
        return "intel" if answer else "none"

    print("No GPU detected — using CPU-only mode.")
    return "none"


def resolve_environment_choice(
    *,
    provided: str | None,
    interactive: bool,
) -> str:
    """Determine environment: 'dev' or 'prod'."""
    if provided is not None:
        if provided not in {"dev", "prod"}:
            raise ValueError("--environment must be 'dev' or 'prod'")
        return provided

    if not interactive:
        return "prod"

    answer = prompt_text("Environment (dev/prod)", default="prod")
    if answer.lower() in {"dev", "development"}:
        return "dev"
    return "prod"


def resolve_ssl_choice(
    *,
    ssl_provided: bool | None,
    domain_provided: str | None,
    interactive: bool,
) -> tuple[bool, str | None]:
    """Determine SSL/TLS choice and domain."""
    if ssl_provided is not None:
        if ssl_provided and not domain_provided and not interactive:
            raise ValueError("--domain is required when --ssl is used non-interactively")
        if ssl_provided and not domain_provided:
            domain = prompt_text("Domain for Let's Encrypt certificate (e.g. aithena.example.com)")
            return True, domain
        return ssl_provided, domain_provided

    if not interactive:
        return False, None

    want_ssl = prompt_yes_no("Enable SSL with Let's Encrypt?", default=False)
    if not want_ssl:
        return False, None

    domain = prompt_text("Domain for Let's Encrypt certificate (e.g. aithena.example.com)")
    return True, domain


VALID_TOPOLOGIES = {"single-node", "distributed"}


def resolve_topology_choice(
    *,
    provided: str | None,
    existing: str | None,
    interactive: bool,
) -> str:
    """Determine Solr topology: 'single-node' or 'distributed'."""
    if provided is not None:
        if provided not in VALID_TOPOLOGIES:
            raise ValueError("--topology must be 'single-node' or 'distributed'")
        return provided

    if existing in VALID_TOPOLOGIES:
        if not interactive:
            return existing
        # Show current selection to user and let them confirm or change
        print(f"\nCurrent topology: {existing}")

    if not interactive:
        return existing if existing in VALID_TOPOLOGIES else "distributed"

    print("\nSelect deployment topology:")
    print("  1) single-node  — 1 Solr + 1 ZooKeeper (recommended for dev/small deployments)")
    print("  2) distributed  — 3 Solr + 3 ZooKeeper (recommended for production)")
    while True:
        answer = prompt_text("Topology", default="2")
        if answer in {"1", "single-node"}:
            return "single-node"
        if answer in {"2", "distributed"}:
            return "distributed"
        print("Please enter 1 or 2 (or 'single-node'/'distributed').")


def prompt_yes_no(label: str, *, default: bool = True) -> bool:
    """Prompt the user for a yes/no answer."""
    hint = "(Y/n)" if default else "(y/N)"
    raw = input(f"{label} {hint}: ").strip().lower()
    if not raw:
        return default
    return raw in {"y", "yes"}


def generate_start_script(
    *,
    root: Path,
    environment: str,
    gpu: str,
    ssl: bool,
    domain: str | None,
    topology: str,
) -> Path:
    """Generate ./start.sh with the correct docker compose file chain."""
    compose_files: list[str] = []

    if environment == "prod":
        compose_files.append("-f docker-compose.yml")
        compose_files.append("-f docker/compose.prod.yml")
    else:
        compose_files.append("-f docker-compose.yml")
        compose_files.append("-f docker/compose.dev-ports.yml")

    if gpu == "nvidia":
        compose_files.append("-f docker/compose.gpu-nvidia.yml")
    elif gpu == "intel":
        compose_files.append("-f docker/compose.gpu-intel.yml")

    if ssl:
        compose_files.append("-f docker/compose.ssl.yml")

    if topology == "single-node":
        compose_files.append("-f docker/compose.single-node.yml")

    compose_chain = " ".join(compose_files)

    ssl_setup_block = ""
    if ssl and domain:
        ssl_setup_block = f"""
# Ensure certbot directories exist for Let's Encrypt
sudo mkdir -p /source/volumes/certbot-data/{{conf,www}}

# Bootstrap initial certificate (first run only)
if [ ! -d "/source/volumes/certbot-data/conf/live/{domain}" ]; then
  echo "Bootstrapping Let's Encrypt certificate for {domain}..."
  docker compose {compose_chain} run --rm certbot certonly \\
    --webroot -w /var/www/certbot \\
    -d {domain} --agree-tos --non-interactive \\
    --register-unsafely-without-email
fi
"""

    build_flag = " --build" if environment == "dev" else ""

    ssl_label = "enabled" if ssl else "disabled"
    echo_msg = f"Starting Aithena ({environment} mode, GPU: {gpu}, SSL: {ssl_label}, Topology: {topology})..."

    script_content = f"""#!/usr/bin/env bash
# Generated by installer/setup.py — re-run the installer to regenerate.
set -euo pipefail
cd "$(dirname "$0")"
{ssl_setup_block}
echo "{echo_msg}"
docker compose {compose_chain} up -d{build_flag}
"""

    script_path = root / "start.sh"
    script_path.write_text(script_content, encoding="utf-8")
    script_path.chmod(script_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return script_path


def run_setup(
    config: InstallerConfig,
    *,
    interactive: bool,
    secret_factory: Callable[[int], str],
) -> SetupResult:
    env_path = config.env_path.resolve()
    existing_env = load_env_file(env_path)

    # Environment choice (dev/prod)
    environment = resolve_environment_choice(
        provided=config.environment,
        interactive=interactive,
    )

    # GPU detection and choice
    gpu = resolve_gpu_choice(
        provided=config.gpu,
        interactive=interactive,
    )

    # SSL choice
    ssl, domain = resolve_ssl_choice(
        ssl_provided=config.ssl,
        domain_provided=config.domain,
        interactive=interactive,
    )

    # Topology choice (single-node vs distributed)
    topology = resolve_topology_choice(
        provided=config.topology,
        existing=existing_env.get("SOLR_TOPOLOGY"),
        interactive=interactive,
    )

    library_path = resolve_value(
        provided=config.library_path,
        existing=existing_env.get("BOOKS_PATH") or existing_env.get("BOOK_LIBRARY_PATH"),
        interactive=interactive,
        prompt_label="Book library path",
        validator=resolve_library_path,
        flag_name="--library-path",
    )
    admin_user = resolve_value(
        provided=config.admin_user,
        existing=existing_env.get("AUTH_ADMIN_USERNAME", DEFAULT_ADMIN_USERNAME),
        interactive=interactive,
        prompt_label="Admin username",
        validator=normalize_username,
        flag_name="--admin-user",
    )
    existing_auth_db_path = existing_env.get("AUTH_DB_DIR")
    if existing_auth_db_path is not None:
        container_auth_db_name = Path(existing_env.get("AUTH_DB_PATH", DEFAULT_CONTAINER_AUTH_DB_PATH)).name
        existing_auth_db_path = str(Path(existing_auth_db_path).expanduser() / container_auth_db_name)
    else:
        existing_auth_db_path = existing_env.get("AUTH_DB_PATH", str(DEFAULT_AUTH_DB_PATH))

    auth_db_path = resolve_value(
        provided=str(config.auth_db_path) if config.auth_db_path is not None else None,
        existing=existing_auth_db_path,
        interactive=False,
        prompt_label="Auth DB path",
        validator=resolve_auth_db_path,
        flag_name="--auth-db-path",
    )

    # Auto-suggest origin based on SSL choice
    if ssl and domain:
        origin_default = f"https://{domain}"
    else:
        origin_default = (
            existing_env.get("PUBLIC_ORIGIN") or existing_env.get("CORS_ORIGINS", DEFAULT_PUBLIC_ORIGIN).split(",")[0]
        )
    origin = resolve_value(
        provided=config.origin,
        existing=origin_default,
        interactive=interactive,
        prompt_label="Public origin URL",
        validator=normalize_origin,
        flag_name="--origin",
    )

    user_exists = find_user(auth_db_path, admin_user) is not None
    admin_password = resolve_password(
        provided=config.admin_password,
        interactive=interactive,
        can_keep_existing=user_exists and not config.reset,
    )

    env_values, generated_jwt_secret, generated_solr_passwords = build_env_values(
        library_path=library_path,
        auth_db_path=auth_db_path,
        origin=origin,
        admin_user=admin_user,
        admin_password=admin_password,
        existing_env=existing_env,
        secret_factory=secret_factory,
        reset=config.reset,
    )

    # Add NGINX_HOST for SSL setups
    if ssl and domain:
        env_values["NGINX_HOST"] = domain

    # Store topology selection
    env_values["SOLR_TOPOLOGY"] = topology

    # Set sensible Solr defaults based on topology
    if topology == "single-node":
        env_values.setdefault("SOLR_NUM_SHARDS", "1")
        env_values.setdefault("SOLR_REPLICATION_FACTOR", "1")
    else:
        env_values.setdefault("SOLR_NUM_SHARDS", "1")
        env_values.setdefault("SOLR_REPLICATION_FACTOR", "3")

    admin_action = bootstrap_admin_user(auth_db_path, admin_user, admin_password, reset=config.reset)
    write_env_file(env_path, env_values)

    # Generate start.sh
    start_script = generate_start_script(
        root=ROOT,
        environment=environment,
        gpu=gpu,
        ssl=ssl,
        domain=domain,
        topology=topology,
    )

    return SetupResult(
        env_path=env_path,
        auth_db_path=auth_db_path,
        library_path=library_path,
        origin=origin,
        admin_user=admin_user,
        admin_action=admin_action,
        generated_jwt_secret=generated_jwt_secret,
        generated_solr_passwords=generated_solr_passwords,
        environment=environment,
        gpu=gpu,
        ssl=ssl,
        domain=domain,
        topology=topology,
        start_script=start_script,
    )


def resolve_value(
    *,
    provided: str | None,
    existing: str | None,
    interactive: bool,
    prompt_label: str,
    validator: Callable[[str], object],
    flag_name: str,
):
    if provided is not None:
        return validator(provided)

    if interactive:
        while True:
            raw_value = prompt_text(prompt_label, default=existing)
            try:
                return validator(raw_value)
            except ValueError as exc:
                print(f"Error: {exc}")

    if existing is not None:
        return validator(existing)

    raise ValueError(f"{flag_name} is required when stdin is not interactive")


def resolve_password(*, provided: str | None, interactive: bool, can_keep_existing: bool) -> str | None:
    if provided is not None:
        if not provided:
            raise ValueError("--admin-password cannot be empty")
        return provided

    if not interactive:
        if can_keep_existing:
            return None
        raise ValueError("--admin-password is required when stdin is not interactive")

    return prompt_password(can_keep_existing=can_keep_existing)


def prompt_text(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    raw_value = input(f"{label}{suffix}: ").strip()
    if raw_value:
        return raw_value
    if default is not None:
        return default
    return raw_value


def prompt_password(*, can_keep_existing: bool) -> str | None:
    while True:
        prompt = "Admin password"
        if can_keep_existing:
            prompt += " (leave blank to keep the existing password)"
        prompt += ": "
        password = getpass.getpass(prompt)
        if not password and can_keep_existing:
            return None
        if not password:
            print("Error: Admin password is required")
            continue
        confirmation = getpass.getpass("Confirm admin password: ")
        if password != confirmation:
            print("Error: Passwords do not match")
            continue
        return password


def read_repo_version() -> str:
    version_path = ROOT / "VERSION"
    if not version_path.exists():
        return "dev"
    return version_path.read_text(encoding="utf-8").strip() or "dev"


def read_git_commit() -> str:
    git_executable = shutil.which("git")
    if git_executable is None:
        return "unknown"

    completed = subprocess.run(  # noqa: S603
        [git_executable, "rev-parse", "HEAD"],
        cwd=ROOT,
        capture_output=True,
        check=False,
        text=True,
    )
    commit = completed.stdout.strip()
    return commit or "unknown"


def utc_now_iso() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _quote_env_value(value: str) -> str:
    sanitized = value.replace("\n", "").replace("\r", "").replace("\x00", "")
    if any(character.isspace() for character in sanitized) or "#" in sanitized:
        escaped = sanitized.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return sanitized


def _unquote_env_value(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        inner = value[1:-1]
        if value[0] == '"':
            return inner.replace('\\"', '"').replace("\\\\", "\\")
        return inner
    return value


def ensure_runtime_dependencies(argv: list[str]) -> None:
    try:
        from aithena_common.passwords import hash_password as _probe  # noqa: PLC0415, F401
    except ImportError as exc:
        if os.environ.get("AITHENA_INSTALLER_UV") == "1":
            raise RuntimeError("aithena-common is not installed. Run `cd installer && uv sync` first.") from exc

        uv_executable = shutil.which("uv")
        if uv_executable is None:
            raise RuntimeError("aithena-common is not installed and uv is not available.") from exc

        completed = subprocess.run(  # noqa: S603
            [
                uv_executable,
                "run",
                "--project",
                str(ROOT / "installer"),
                "python",
                "-m",
                "installer.setup",
                *argv,
            ],
            cwd=ROOT,
            check=False,
            env={**os.environ, "AITHENA_INSTALLER_UV": "1"},
        )
        raise SystemExit(completed.returncode) from exc


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run the first-run Aithena installer.")
    parser.add_argument("--library-path", help="Host path to the PDF library directory")
    parser.add_argument("--admin-user", help="Bootstrap admin username")
    parser.add_argument("--admin-password", help="Bootstrap admin password")
    parser.add_argument("--origin", help="Public origin URL, for example http://localhost")
    parser.add_argument("--auth-db-path", help="Persistent SQLite auth database path")
    parser.add_argument("--env-file", default=str(DEFAULT_ENV_PATH), help="Path to the .env file to write")
    parser.add_argument("--reset", action="store_true", help="Recreate the auth DB before seeding the admin user")
    parser.add_argument("--environment", choices=["dev", "prod"], help="Deployment environment (dev or prod)")
    parser.add_argument("--gpu", choices=["nvidia", "intel", "none"], help="GPU acceleration mode")
    parser.add_argument("--ssl", action="store_true", default=None, help="Enable SSL with Let's Encrypt")
    parser.add_argument("--no-ssl", dest="ssl", action="store_false", help="Disable SSL")
    parser.add_argument("--domain", help="Domain name for SSL certificate")
    parser.add_argument(
        "--topology",
        choices=["single-node", "distributed"],
        help="Solr topology: single-node (1 Solr + 1 ZK) or distributed (3 Solr + 3 ZK)",
    )
    return parser


def print_summary(result: SetupResult) -> None:
    secret_status = "generated" if result.generated_jwt_secret else "kept existing"
    solr_status = "generated" if result.generated_solr_passwords else "kept existing"
    print("\nAithena setup complete.")
    print(f"- .env: {result.env_path}")
    print(f"- Auth DB: {result.auth_db_path}")
    print(f"- Admin user: {result.admin_user} ({result.admin_action})")
    # Security note: prints status string only, NOT the actual JWT secret value
    print(f"- JWT secret: {secret_status}")  # noqa: S108 — logs status, not sensitive data
    print(f"- Solr passwords: {solr_status}")  # noqa: S108 — logs status, not sensitive data
    print(f"- Environment: {result.environment}")
    print(f"- GPU: {result.gpu}")
    ssl_info = f"enabled ({result.domain})" if result.ssl else "disabled"
    print(f"- SSL: {ssl_info}")
    print(f"- Topology: {result.topology}")
    if result.start_script:
        print(f"- Start script: {result.start_script}")
    print("\nNext steps:")
    print("1. Review the generated .env file if you need to tweak paths, origin, or service credentials.")
    print("2. Keep the generated auth storage directory in place before starting Docker Compose.")
    if result.start_script:
        print("3. Start the stack with: ./start.sh")
    else:
        print("3. Start or restart the stack with: docker compose up -d")
    print(f"4. Open {result.origin} and sign in as {result.admin_user}.")


def main(argv: list[str] | None = None) -> int:
    argv_list = list(argv) if argv is not None else sys.argv[1:]
    parser = build_parser()
    args = parser.parse_args(argv_list)
    config = InstallerConfig(
        library_path=args.library_path,
        admin_user=args.admin_user,
        admin_password=args.admin_password,
        origin=args.origin,
        auth_db_path=Path(args.auth_db_path).expanduser() if args.auth_db_path else None,
        env_path=Path(args.env_file).expanduser(),
        reset=args.reset,
        environment=args.environment,
        gpu=args.gpu,
        ssl=args.ssl,
        domain=args.domain,
        topology=args.topology,
    )
    interactive = sys.stdin.isatty() and sys.stdout.isatty()

    try:
        ensure_runtime_dependencies(argv_list)
        result = run_setup(config, interactive=interactive, secret_factory=secrets.token_urlsafe)
    except (OSError, RuntimeError, sqlite3.Error, ValueError) as exc:
        print(f"Setup failed: {exc}", file=sys.stderr)
        return 1

    print_summary(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
