from __future__ import annotations

import argparse
import contextlib
import getpass
import os
import secrets
import shutil
import sqlite3
import subprocess
import sys
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
SOLR_SEARCH_DIR = ROOT / "solr-search"
if str(SOLR_SEARCH_DIR) not in sys.path:
    sys.path.append(str(SOLR_SEARCH_DIR))

DEFAULT_AUTH_DB_PATH = Path.home() / ".local" / "share" / "aithena" / "auth" / "users.db"
DEFAULT_CONTAINER_AUTH_DB_PATH = "/data/auth/users.db"
DEFAULT_AUTH_COOKIE_NAME = "aithena_auth"
DEFAULT_AUTH_JWT_TTL = "24h"
DEFAULT_PUBLIC_ORIGIN = "http://localhost"
DEFAULT_ENV_PATH = ROOT / ".env"
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_RABBITMQ_USER = "aithena"
INSECURE_JWT_SECRETS = {"", "change-me", "development-only-change-me", "generate-with-installer"}
INSECURE_RABBITMQ_USERS = {"", "change-me", "guest", "generate-with-installer"}
INSECURE_RABBITMQ_PASSWORDS = {"", "change-me", "guest", "generate-with-installer"}
INSECURE_REDIS_PASSWORDS = {"", "change-me", "generate-with-installer"}
ENV_COMMENTS: list[tuple[str, str]] = [
    ("BOOKS_PATH", "Path to your book library on the host"),
    ("BOOK_LIBRARY_PATH", "Compatibility alias for installer consumers"),
    ("PUBLIC_ORIGIN", "Public origin used by browsers (scheme + host)"),
    ("CORS_ORIGINS", "Comma-separated CORS origins consumed by solr-search"),
    ("AUTH_DB_DIR", "Host directory mounted into the container for auth storage"),
    ("AUTH_DB_PATH", "SQLite auth database path inside the container"),
    ("AUTH_JWT_SECRET", "JWT signing secret generated by the installer"),
    ("AUTH_JWT_TTL", "JWT lifetime accepted by solr-search/auth.py (e.g. 24h)"),
    ("AUTH_COOKIE_NAME", "HTTP cookie name used for browser auth"),
    ("AUTH_ADMIN_USERNAME", "Installer-managed bootstrap admin username"),
    ("RABBITMQ_USER", "RabbitMQ broker/admin username used by Compose and admin surfaces"),
    ("RABBITMQ_PASS", "RabbitMQ broker/admin password generated by the installer"),
    ("REDIS_PASSWORD", "Redis password applied via redis-server --requirepass"),
    ("VERSION", "Container build metadata (defaults to VERSION file)"),
    ("GIT_COMMIT", "Container build metadata (defaults to current HEAD)"),
    ("BUILD_DATE", "Container build metadata timestamp"),
]


@dataclass(frozen=True)
class InstallerConfig:
    library_path: str | None = None
    admin_user: str | None = None
    admin_password: str | None = None
    origin: str | None = None
    auth_db_path: Path | None = None
    env_path: Path = DEFAULT_ENV_PATH
    reset: bool = False


@dataclass(frozen=True)
class SetupResult:
    env_path: Path
    auth_db_path: Path
    library_path: Path
    origin: str
    admin_user: str
    admin_action: str
    generated_jwt_secret: bool


def load_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    env_values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#") or "=" not in raw_line:
            continue
        key, value = raw_line.split("=", 1)
        env_values[key.strip()] = _unquote_env_value(value.strip())
    return env_values


def write_env_file(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# Generated by installer/setup.py on {utc_now_iso()}", ""]
    for key, comment in ENV_COMMENTS:
        value = values[key]
        lines.append(f"# {comment}")
        lines.append(f"{key}={_quote_env_value(value)}")
        lines.append("")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    with contextlib.suppress(OSError):
        path.chmod(0o600)


def resolve_library_path(raw_value: str) -> Path:
    candidate = Path(raw_value).expanduser()
    if candidate.exists() and not candidate.is_dir():
        raise ValueError("Book library path must point to a directory")
    candidate.mkdir(parents=True, exist_ok=True)
    return candidate.resolve()


def resolve_auth_db_path(raw_value: str) -> Path:
    candidate = Path(raw_value).expanduser()
    if candidate.exists() and candidate.is_dir():
        raise ValueError("Auth DB path must be a file path, not a directory")
    return candidate.resolve()


def normalize_username(raw_value: str) -> str:
    username = raw_value.strip()
    if not username:
        raise ValueError("Admin username is required")
    if any(c in username for c in ("\n", "\r", "\x00", "=")):
        raise ValueError("Username contains invalid characters")
    return username


def normalize_origin(raw_value: str) -> str:
    parsed = urlparse(raw_value.strip())
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError("Origin must be a full http:// or https:// URL")
    if parsed.params or parsed.query or parsed.fragment:
        raise ValueError("Origin must not include params, query strings, or fragments")
    cleaned_path = parsed.path.rstrip("/")
    if cleaned_path:
        raise ValueError("Origin must not include a path")
    return f"{parsed.scheme}://{parsed.netloc}".rstrip("/")


def bootstrap_admin_user(
    db_path: Path,
    username: str,
    password: str | None,
    *,
    reset: bool = False,
) -> str:
    if reset and db_path.exists():
        db_path.unlink()

    hash_password_fn, init_auth_db_fn = load_auth_helpers()
    init_auth_db_fn(db_path)
    with contextlib.suppress(OSError):
        db_path.chmod(0o600)
    normalized_username = normalize_username(username)

    with sqlite3.connect(db_path) as connection:
        connection.row_factory = sqlite3.Row
        existing_row = connection.execute(
            "SELECT id, role FROM users WHERE username = ?",
            (normalized_username,),
        ).fetchone()

        if existing_row is None and password is None:
            raise ValueError("Admin password is required when creating a new admin user")

        if existing_row is None:
            connection.execute(
                "INSERT INTO users (username, password_hash, role) VALUES (?, ?, ?)",
                (normalized_username, hash_password_fn(password or ""), "admin"),
            )
            connection.commit()
            return "created"

        if password is None and existing_row["role"] == "admin":
            return "kept"

        if password is None:
            connection.execute(
                "UPDATE users SET role = ? WHERE id = ?",
                ("admin", int(existing_row["id"])),
            )
            connection.commit()
            return "updated"

        connection.execute(
            "UPDATE users SET password_hash = ?, role = ? WHERE id = ?",
            (hash_password_fn(password), "admin", int(existing_row["id"])),
        )
        connection.commit()
        return "updated"


def find_user(db_path: Path, username: str) -> dict[str, str | int] | None:
    if not db_path.exists():
        return None

    with sqlite3.connect(db_path) as connection:
        connection.row_factory = sqlite3.Row
        row = connection.execute(
            "SELECT id, username, role FROM users WHERE username = ?",
            (normalize_username(username),),
        ).fetchone()
        if row is None:
            return None
        return {"id": int(row["id"]), "username": str(row["username"]), "role": str(row["role"])}


def load_auth_helpers() -> tuple[Callable[[str], str], Callable[[Path], None]]:
    try:
        from auth import hash_password, init_auth_db  # noqa: PLC0415
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "Missing auth dependencies. Run `uv run --project solr-search python -m installer` "
            "or `cd solr-search && uv sync` before invoking the installer."
        ) from exc
    return hash_password, init_auth_db


def build_env_values(
    *,
    library_path: Path,
    auth_db_path: Path,
    origin: str,
    admin_user: str,
    existing_env: dict[str, str],
    secret_factory: Callable[[int], str],
    reset: bool,
) -> tuple[dict[str, str], bool]:
    existing_secret = existing_env.get("AUTH_JWT_SECRET", "")
    generated_jwt_secret = reset or existing_secret in INSECURE_JWT_SECRETS
    auth_jwt_secret = existing_secret or secret_factory(32)
    if generated_jwt_secret:
        auth_jwt_secret = secret_factory(32)

    existing_rabbitmq_user = existing_env.get("RABBITMQ_USER", "").strip()
    rabbitmq_user = existing_rabbitmq_user or DEFAULT_RABBITMQ_USER
    if reset or existing_rabbitmq_user in INSECURE_RABBITMQ_USERS:
        rabbitmq_user = DEFAULT_RABBITMQ_USER

    existing_rabbitmq_pass = existing_env.get("RABBITMQ_PASS", "")
    rabbitmq_pass = existing_rabbitmq_pass
    if reset or existing_rabbitmq_pass in INSECURE_RABBITMQ_PASSWORDS:
        rabbitmq_pass = secret_factory(32)

    existing_redis_password = existing_env.get("REDIS_PASSWORD", "")
    redis_password = existing_redis_password
    if reset or existing_redis_password in INSECURE_REDIS_PASSWORDS:
        redis_password = secret_factory(32)

    env_values = {
        "BOOKS_PATH": str(library_path),
        "BOOK_LIBRARY_PATH": str(library_path),
        "PUBLIC_ORIGIN": origin,
        "CORS_ORIGINS": origin,
        "AUTH_DB_DIR": str(auth_db_path.parent),
        "AUTH_DB_PATH": f"/data/auth/{auth_db_path.name}",
        "AUTH_JWT_SECRET": auth_jwt_secret,
        "AUTH_JWT_TTL": existing_env.get("AUTH_JWT_TTL", DEFAULT_AUTH_JWT_TTL),
        "AUTH_COOKIE_NAME": existing_env.get("AUTH_COOKIE_NAME", DEFAULT_AUTH_COOKIE_NAME),
        "AUTH_ADMIN_USERNAME": admin_user,
        "RABBITMQ_USER": rabbitmq_user,
        "RABBITMQ_PASS": rabbitmq_pass,
        "REDIS_PASSWORD": redis_password,
        "VERSION": existing_env.get("VERSION", read_repo_version()),
        "GIT_COMMIT": existing_env.get("GIT_COMMIT", read_git_commit()),
        "BUILD_DATE": existing_env.get("BUILD_DATE", utc_now_iso()),
    }
    return env_values, generated_jwt_secret


def run_setup(
    config: InstallerConfig,
    *,
    interactive: bool,
    secret_factory: Callable[[int], str],
) -> SetupResult:
    env_path = config.env_path.resolve()
    existing_env = load_env_file(env_path)

    library_path = resolve_value(
        provided=config.library_path,
        existing=existing_env.get("BOOKS_PATH") or existing_env.get("BOOK_LIBRARY_PATH"),
        interactive=interactive,
        prompt_label="Book library path",
        validator=resolve_library_path,
        flag_name="--library-path",
    )
    admin_user = resolve_value(
        provided=config.admin_user,
        existing=existing_env.get("AUTH_ADMIN_USERNAME", DEFAULT_ADMIN_USERNAME),
        interactive=interactive,
        prompt_label="Admin username",
        validator=normalize_username,
        flag_name="--admin-user",
    )
    existing_auth_db_path = existing_env.get("AUTH_DB_DIR")
    if existing_auth_db_path is not None:
        container_auth_db_name = Path(
            existing_env.get("AUTH_DB_PATH", DEFAULT_CONTAINER_AUTH_DB_PATH)
        ).name
        existing_auth_db_path = str(Path(existing_auth_db_path).expanduser() / container_auth_db_name)
    else:
        existing_auth_db_path = existing_env.get("AUTH_DB_PATH", str(DEFAULT_AUTH_DB_PATH))

    auth_db_path = resolve_value(
        provided=str(config.auth_db_path) if config.auth_db_path is not None else None,
        existing=existing_auth_db_path,
        interactive=False,
        prompt_label="Auth DB path",
        validator=resolve_auth_db_path,
        flag_name="--auth-db-path",
    )
    origin_default = existing_env.get("PUBLIC_ORIGIN") or existing_env.get(
        "CORS_ORIGINS", DEFAULT_PUBLIC_ORIGIN
    ).split(",")[0]
    origin = resolve_value(
        provided=config.origin,
        existing=origin_default,
        interactive=interactive,
        prompt_label="Public origin URL",
        validator=normalize_origin,
        flag_name="--origin",
    )

    user_exists = find_user(auth_db_path, admin_user) is not None
    admin_password = resolve_password(
        provided=config.admin_password,
        interactive=interactive,
        can_keep_existing=user_exists and not config.reset,
    )

    env_values, generated_jwt_secret = build_env_values(
        library_path=library_path,
        auth_db_path=auth_db_path,
        origin=origin,
        admin_user=admin_user,
        existing_env=existing_env,
        secret_factory=secret_factory,
        reset=config.reset,
    )

    admin_action = bootstrap_admin_user(auth_db_path, admin_user, admin_password, reset=config.reset)
    write_env_file(env_path, env_values)

    return SetupResult(
        env_path=env_path,
        auth_db_path=auth_db_path,
        library_path=library_path,
        origin=origin,
        admin_user=admin_user,
        admin_action=admin_action,
        generated_jwt_secret=generated_jwt_secret,
    )


def resolve_value(
    *,
    provided: str | None,
    existing: str | None,
    interactive: bool,
    prompt_label: str,
    validator: Callable[[str], object],
    flag_name: str,
):
    if provided is not None:
        return validator(provided)

    if interactive:
        while True:
            raw_value = prompt_text(prompt_label, default=existing)
            try:
                return validator(raw_value)
            except ValueError as exc:
                print(f"Error: {exc}")

    if existing is not None:
        return validator(existing)

    raise ValueError(f"{flag_name} is required when stdin is not interactive")


def resolve_password(*, provided: str | None, interactive: bool, can_keep_existing: bool) -> str | None:
    if provided is not None:
        if not provided:
            raise ValueError("--admin-password cannot be empty")
        return provided

    if not interactive:
        if can_keep_existing:
            return None
        raise ValueError("--admin-password is required when stdin is not interactive")

    return prompt_password(can_keep_existing=can_keep_existing)


def prompt_text(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    raw_value = input(f"{label}{suffix}: ").strip()
    if raw_value:
        return raw_value
    if default is not None:
        return default
    return raw_value


def prompt_password(*, can_keep_existing: bool) -> str | None:
    while True:
        prompt = "Admin password"
        if can_keep_existing:
            prompt += " (leave blank to keep the existing password)"
        prompt += ": "
        password = getpass.getpass(prompt)
        if not password and can_keep_existing:
            return None
        if not password:
            print("Error: Admin password is required")
            continue
        confirmation = getpass.getpass("Confirm admin password: ")
        if password != confirmation:
            print("Error: Passwords do not match")
            continue
        return password


def read_repo_version() -> str:
    version_path = ROOT / "VERSION"
    if not version_path.exists():
        return "dev"
    return version_path.read_text(encoding="utf-8").strip() or "dev"


def read_git_commit() -> str:
    git_executable = shutil.which("git")
    if git_executable is None:
        return "unknown"

    completed = subprocess.run(  # noqa: S603
        [git_executable, "rev-parse", "HEAD"],
        cwd=ROOT,
        capture_output=True,
        check=False,
        text=True,
    )
    commit = completed.stdout.strip()
    return commit or "unknown"


def utc_now_iso() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _quote_env_value(value: str) -> str:
    sanitized = value.replace("\n", "").replace("\r", "").replace("\x00", "")
    if any(character.isspace() for character in sanitized) or "#" in sanitized:
        escaped = sanitized.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return sanitized


def _unquote_env_value(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        inner = value[1:-1]
        if value[0] == '"':
            return inner.replace('\\"', '"').replace('\\\\', '\\')
        return inner
    return value


def ensure_runtime_dependencies(argv: list[str]) -> None:
    try:
        load_auth_helpers()
    except RuntimeError as exc:
        if os.environ.get("AITHENA_INSTALLER_UV") == "1":
            raise

        uv_executable = shutil.which("uv")
        if uv_executable is None:
            raise

        completed = subprocess.run(  # noqa: S603
            [
                uv_executable,
                "run",
                "--project",
                str(SOLR_SEARCH_DIR),
                "python",
                "-m",
                "installer.setup",
                *argv,
            ],
            cwd=ROOT,
            check=False,
            env={**os.environ, "AITHENA_INSTALLER_UV": "1"},
        )
        raise SystemExit(completed.returncode) from exc


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run the first-run Aithena installer.")
    parser.add_argument("--library-path", help="Host path to the PDF library directory")
    parser.add_argument("--admin-user", help="Bootstrap admin username")
    parser.add_argument("--admin-password", help="Bootstrap admin password")
    parser.add_argument("--origin", help="Public origin URL, for example http://localhost")
    parser.add_argument("--auth-db-path", help="Persistent SQLite auth database path")
    parser.add_argument("--env-file", default=str(DEFAULT_ENV_PATH), help="Path to the .env file to write")
    parser.add_argument("--reset", action="store_true", help="Recreate the auth DB before seeding the admin user")
    return parser


def print_summary(result: SetupResult) -> None:
    secret_status = "generated" if result.generated_jwt_secret else "kept existing"
    print("\nAithena setup complete.")
    print(f"- .env: {result.env_path}")
    print(f"- Auth DB: {result.auth_db_path}")
    print(f"- Admin user: {result.admin_user} ({result.admin_action})")
    print(f"- JWT secret: {secret_status}")
    print("\nNext steps:")
    print("1. Review the generated .env file if you need to tweak paths, origin, or service credentials.")
    print("2. Keep the generated auth storage directory in place before starting Docker Compose.")
    print("3. Start or restart the stack with: docker compose up -d")
    print(f"4. Open {result.origin} and sign in as {result.admin_user}.")


def main(argv: list[str] | None = None) -> int:
    argv_list = list(argv) if argv is not None else sys.argv[1:]
    parser = build_parser()
    args = parser.parse_args(argv_list)
    config = InstallerConfig(
        library_path=args.library_path,
        admin_user=args.admin_user,
        admin_password=args.admin_password,
        origin=args.origin,
        auth_db_path=Path(args.auth_db_path).expanduser() if args.auth_db_path else None,
        env_path=Path(args.env_file).expanduser(),
        reset=args.reset,
    )
    interactive = sys.stdin.isatty() and sys.stdout.isatty()

    try:
        ensure_runtime_dependencies(argv_list)
        result = run_setup(config, interactive=interactive, secret_factory=secrets.token_urlsafe)
    except (OSError, RuntimeError, sqlite3.Error, ValueError) as exc:
        print(f"Setup failed: {exc}", file=sys.stderr)
        return 1

    print_summary(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
